Config = Config or {}
_itemsSource = _itemsSource or {}

function hasValue(tbl, value)
	for k, v in ipairs(tbl or {}) do
		if v == value or (type(v) == 'table' and hasValue(v, value)) then
			return true
		end
	end
	return false
end

Config.StartItems = {
	{ name = 'govid', count = 1 },
	{ name = 'phone', count = 1 },
	{ name = 'giftbox', count = 1 },
}

Config.ShopItemSets = {
	[1] = { -- General Stores like 24/7 etc..
		'sandwich',
		'sandwich_egg',
		'water',
		'bandage',
		'cigarette_pack',
		'coffee',
		'soda',
		'energy_pepe',
		'chocolate_bar',
		'donut_stack',
		'crisp',
		'rolling_paper',
		{ item = 'moonshine_jar', count = 50, price = 75 },
		-- 'egg_basket',
	},
	[2] = { -- Hardware
		'screwdriver',
		'WEAPON_HAMMER',
		'WEAPON_CROWBAR',
		'WEAPON_GOLFCLUB',
		'repairkit',
		'fertilizer_nitrogen',
		'fertilizer_phosphorus',
		'fertilizer_potassium',
		'camping_chair',
		'beanbag',
		'plastic_wrap',
		'baggy',
		'binoculars',
		'metal_detector',
		'WEAPON_SHOVEL',
		'cloth',
		'pipe',
		'nails',
		'drill',
		'battery_acid',
		'lockpick',
		'smallbackpack',
		'mediumbackpack',
		'largebackpack',
		-- 'egg_basket',
	},
	[3] = { -- Burger Shot Supplies
		'cup', 
		'bun', 
		'patty', 
		'pickle' 
	},
	[4] = {  -- Ammunation
		'armor',
		'heavyarmor',
		'WEAPON_COMBATPISTOL',
		'AMMO_PISTOL',
		'WEAPON_BAT',
		'WEAPON_KNIFE',
		'KATANA',
	},
	[5] = { -- Electronics Store
		'phone',
		'radio_shitty',
		'camera',
		'electronics_kit',
		'hackingdevice',
		'gpshackingdevice',
		'boostingtablet',
	},
	[6] = { -- Police Armory
		'pdarmor',
		'ifak',
		'megaphone',
		'pdhandcuffs',
		'spikes',
		'WEAPON_FLASHLIGHT',
		'WEAPON_TASER',
		'WEAPON_BEANBAG',
		'WEAPON_COMBATPISTOL',
		'WEAPON_HK416B',
		'AMMO_PISTOL_PD',
		'AMMO_SHOTGUN_PD',
		'AMMO_SMG_PD',
		'AMMO_RIFLE_PD',
		'AMMO_STUNGUN',
		'radio',
		'binoculars',
		'camera',
		'phone',
		'WEAPON_FLASHBANG',
		-- 'WEAPON_SMOKEGRENADE',
		'bodycam',
		'dashcam',
		'pd_duress_btn',
		'parachute',
	},
	[7] = { -- EMS Armory
		'ifak',
		'traumakit',
		'medicalkit',
		'firstaid',
		'bandage',
		'morphine',
		'radio',
		'phone',
		'scuba_gear',
		'ems_duress_btn',
		'WEAPON_FLASHLIGHT',
		'paramedic_bag',
		'parachute',
		'megaphone'
	},
	[8] = {
		'WEAPON_SNIPERRIFLE2',
		'AMMO_SNIPER',
		'WEAPON_KNIFE',
		'hunting_bait',
		-- 'deer_bait',
		-- 'boar_bait',
		-- 'pig_bait',
		-- 'chicken_bait',
		-- 'rabbit_bait',
		-- 'exotic_bait',
		-- 'egg_basket',
	},
	[9] = { -- DOC Armory
		'pdarmor',
		'pdarmor',
		'traumakit',
		'ifak',
		'pdhandcuffs',
		'WEAPON_FLASHLIGHT',
		'WEAPON_TASER',
		'WEAPON_G17',
		'AMMO_PISTOL_PD',
		'AMMO_RIFLE_PD',
		'AMMO_SHOTGUN_PD',
		'AMMO_STUNGUN',
		'radio',
		'phone',
	},
	[10] = { 'water' }, -- Water Machine
	[11] = { 'coffee' }, -- Coffee Machine
	[12] = { -- Drinks Vending Machines
		'water',
		'soda',
		'energy_pepe',
	},
	[13] = { -- Food Vending Machines
		'chocolate_bar',
		'donut',
		'crisp',
	},
	[14] = {
		'firstaid',
		'bandage',
		-- 'egg_basket',
	},
	[15] = {
		'WEAPON_PETROLCAN',
	},
	[16] = {
		'dough',
		'unk_meat',
		'venison',
		'pork',
		'beef',
		'eggs',
		'loaf',
		'sugar',
		'flour',
		'rice',
		'icing',
		'milk_can',
		'tea_leaf',
		'plastic_cup',
		'coffee_beans',
		'coffee_holder',
		'foodbag',
		'cardboard_box',
		'paper_bag',
		'burgershot_bag',
		'burgershot_cup',
		'bun',
		'water',
		'cheese',
		'jaeger',
		'raspberry_liqueur',
		'sparkling_wine',
		'rum',
		'whiskey',
		'tequila',
		'pineapple',
		'raspberry',
		'peach_juice',
		'coconut_milk',
		'bento_box',
		'keg',
		-- 'egg_basket',
	},
	[17] = {
		'weed_joint',
		'rolling_paper',
	},
	[18] = { -- Liquor Stores
		'vodka',
		'beer',
		'water',
		'bandage',
		'cigarette_pack',
		'coffee',
		'soda',
		'energy_pepe',
		'chocolate_bar',
		'donut',
		'crisp',
		'rolling_paper',
		-- 'egg_basket',
	},
	[19] = {
		'wine_bottle',
	},
	[20] = {
		'fishing_rod',
		'fishing_bait_worm',
		'fishing_bait_lugworm',
		'WEAPON_KNIFE',
		-- 'egg_basket',
	},
	[21] = {
		'fishing_rod',
		'fishing_net',
		'fishing_bait_worm',
		'fishing_bait_lugworm',
		'WEAPON_KNIFE',
		-- 'egg_basket',
	},
	[22] = {
		'personal_plates',
	},
	[23] = {
		'sandwich_blt',
		{ item = 'salad', 				price = 25 },
		{ item = 'chocy_muff', 			price = 15 },
		{ item = 'blueberry_muffin', 	price = 15 },
		'crisp',
		{ item = 'npds_junk_blue_33', 	price = 90 },
		{ item = 'npds_junk_green_33', 	price = 90 },
		{ item = 'npds_junk_red_33', 	price = 90 },
		{ item = 'npds_junk_blue_50', 	price = 105 },
		{ item = 'npds_junk_green_50', 	price = 105 },
		{ item = 'npds_junk_red_50', 	price = 105 },
		{ item = 'npds_slime_01', 		price = 90 },
		{ item = 'npds_slime_02', 		price = 90 },
		{ item = 'npds_slime_03', 		price = 90 },
		{ item = 'npds_slime_04', 		price = 90 },
		{ item = 'npds_slime_05', 		price = 90 },
		'water',
		-- 'egg_basket',
	},
}