_itemsSource["containers"] = {
	{
		name = "coffee_holder",
		label = "Drinks Holder",
		description = "Open Me!",
		price = 3,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 8,
		container = 19,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "foodbag",
		label = "Carrier Bag",
		description = "Open Me!",
		price = 4,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 15,
		container = 21,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "bento_box",
		label = "Bento Box",
		description = "Open Me!",
		price = 4,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 10,
		container = 20,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "cardboard_box",
		label = "Box",
		description = "Open Me!",
		price = 8,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 50,
		container = 22,
		--durability = (60 * 60 * 24 * 60),
		state = "ANIM_box",
	},
	{
		name = "paper_bag",
		label = "Bag",
		description = "Open Me!",
		price = 6,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 10,
		container = 20,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "burgershot_bag",
		label = "Burgershot Bag",
		description = "Have a Murder Meal!",
		price = 20,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 10,
		container = 20,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "card_holder",
		label = "Card Holder",
		description = "Store Those Cards!",
		price = 3,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 2,
		container = 91,
		--durability = (60 * 60 * 24 * 30),
	},

	{
		name = "smallbackpack",
		label = "Small Backpack",
		description = "A small teeny weeny backpack..",
		iconOverride = 'backpack_sml',
		price = 750,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 25,
		container = 5001,
	},
	{
		name = "mediumbackpack",
		label = "Medium Backpack",
		description = "Something more durable!",
		iconOverride = 'backpack_med',
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 50,
		container = 5002,
	},
	{
		name = "largebackpack",
		label = "Large Backpack",
		description = "Wow this is a massive backpack! You know what else is massive?..",
		iconOverride = 'backpack_lrg',
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 100,
		container = 5003,
	},
	{
		name = 'militarypack',
		label = 'Military Backpack',
		description = 'Wow this is a massive backpack! You know what else is massive?..',
		iconOverride = 'backpack_xlrg',
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 100,
		container = 5007,
	},
	{
		name = "paramedic_bag",
		label = "Medical Bag",
		description = "Something more durable, for EMS personal!",
		price = 750,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 25,
		container = 5004,
	},
	{
		name = 'evidence_bag',
		label = 'Evidence Bag',
		description = 'A brown bag, for storing evidence.',
		price = 10,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 8,
		container = 5008,
	},
	{
		name = 'evidence_container',
		label = 'Evidence Container',
		description = 'A big box, for storing evidence.',
		iconOverride = 'evidence-container',
		price = 50,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 50,
		container = 5009,
	},
	{
		name = 'egg_basket',
		label = 'Easter Egg Basket',
		iconOverride = 'easter_egg_basket',
		description = "Don't put all your eggs in one basket",
		price = 1500,
		isUsable = true,
		isStackable = false,
		isDestroyed = false,
		type = 10,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 10,
		container = 5010,
	},
}