_itemsSource["loot"] = {
	{
		name = "valuegoods",
		label = "Valuable Goods",
		description = "Potentially Stolen",
		price = 2450,
		isUsable = false,
		isStackable = 10,
		isDestroyed = true,
		type = 4,
		rarity = 4,
		closeUi = false,
		metalic = false,
		weight = 1,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "goldcoins",
		label = "Gold Coins",
		description = "Potentially Stolen",
		price = 90,
		isUsable = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.1,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "rolex",
		label = "Rolex",
		description = "Potentially Stolen",
		price = 500,
		isUsable = false,
		isStackable = 50,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = false,
		weight = 0.75,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "ring",
		label = "Ring",
		description = "Potentially Stolen",
		price = 185,
		isUsable = false,
		isStackable = 100,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 1,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "chain",
		label = "Gold Chain",
		description = "Potentially Stolen",
		price = 215,
		isUsable = false,
		isStackable = 50,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.5,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "watch",
		label = "Gold Watch",
		description = "Potentially Stolen",
		price = 215,
		isUsable = false,
		isStackable = 50,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 1,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "earrings",
		label = "Gold Earrings",
		description = "Potentially Stolen",
		price = 185,
		isUsable = false,
		isStackable = 100,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.8,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "tv",
		label = "Television",
		description = "Potentially Stolen",
		price = 1800,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 100.0,
		state = "ANIM_tv",
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "big_tv",
		label = "Television",
		description = "Potentially Stolen",
		price = 3400,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 100.0,
		state = "ANIM_bigtv",
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "boombox",
		label = "Boom Box",
		description = "Potentially Stolen",
		price = 300,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 50.0,
		state = "ANIM_boombox",
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "microwave",
		label = "Microwave",
		description = "Potentially Stolen",
		price = 500,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 50.0,
		state = "ANIM_microwave",
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "golfclubs",
		label = "Golf Club Set",
		price = 450,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 100.0,
		state = "ANIM_golfclubs",
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "house_art",
		label = "Painting",
		price = 3600,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = false,
		weight = 100.0,
		state = "ANIM_house_art",
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "pc",
		label = "PC",
		price = 1200,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 80.0,
		state = "ANIM_pc",
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "crushedrock",
		label = "Crushed Rock",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "salvagedparts",
		label = "Salvaged Parts",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
	},
	{
		name = "recycledgoods",
		label = "Recycled Goods",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
	},
	{
		name = "goldore",
		label = "Gold Ore",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
	},
	{
		name = "silverore",
		label = "Silver Ore",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
	},
	{
		name = "ironore",
		label = "Iron Ore",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
	},
	{
		name = "diamond",
		label = "Diamond",
		price = 8000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2.5,
		gemProperties = {
			color = 67,
		},
	},
	{
		name = "emerald",
		label = "Emerald",
		price = 8000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		gemProperties = {
			color = 53,
		},
	},
	{
		name = "sapphire",
		label = "Sapphire",
		price = 6000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		gemProperties = {
			color = 79,
		},
	},
	{
		name = "ruby",
		label = "Ruby",
		price = 6000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		gemProperties = {
			color = 35,
		},
	},
	{
		name = "amethyst",
		label = "Amethyst",
		price = 4000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		gemProperties = {
			color = 145,
		},
	},
	{
		name = "citrine",
		label = "Citrine",
		price = 4000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		gemProperties = {
			color = 38,
		},
	},
	{
		name = "opal",
		label = "Opal",
		price = 1500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		gemProperties = {
			color = 65,
		},
	},
	{
		name = "folded_cash",
		label = "Folded Cash",
		iconOverride = 'moneyfolded',
		price = 100,
		isUsable = false,
		isStackable = 1000,
		type = 14,
		rarity = 1,
		metalic = false,
		weight = 0.01,
	},
	{
		name = "moneyroll",
		label = "Cash Roll",
		price = 100,
		isUsable = false,
		isStackable = 1000,
		type = 14,
		rarity = 1,
		metalic = false,
		weight = 0.01,
	},
	{
		name = "moneyband",
		label = "Bands of Cash",
		price = 1000,
		isUsable = false,
		isStackable = 1000,
		type = 14,
		rarity = 1,
		metalic = false,
		weight = 0.01,
	},
	{
		name = "moneybag",
		label = "Bag of Cash",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 14,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "hide_tier1",
		label = "Animal Hide (Tier 1)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "hide_tier2",
		label = "Animal Hide (Tier 2)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "hide_tier3",
		label = "Animal Hide (Tier 3)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "hide_tier4",
		label = "Animal Hide (Tier 4)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 10),
	},
	{
		name = "fleeca_card",
		label = "Disposable Access Card",
		description = "This seems like it may be usefull",
		price = 10000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 6),
		type = 14,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "crypto_voucher",
		label = "Crypto Voucher",
		price = 0,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "letter",
		label = "Letter",
		description = "Letter to Granny",
		price = 15,
		isUsable = true,
		isStackable = 50,
		isDestroyed = true,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.1,
	},
	{
		name = "letterstack",
		label = "Stack of Letters",
		iconOverride = 'letters',
		price = 75,
		isUsable = true,
		isStackable = 10,
		isDestroyed = true,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 2.5,
	},
	{
		name = 'smlparcel',
		label = 'Small Parcel',
		price = 75,
		isUsable = true,
		isStackable = 5,
		isDestroyed = true,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = 'dl_egg_01',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_01',
		description = "That's a nice egg. 1/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_02',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_02',
		description = "That's a nice egg. 2/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_03',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_03',
		description = "That's a nice egg. 3/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_04',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_04',
		description = "That's a nice egg. 4/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_05',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_05',
		description = "That's a nice egg. 5/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_06',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_06',
		description = "That's a nice egg. 6/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_07',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_07',
		description = "That's a nice egg. 7/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_08',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_08',
		description = "That's a nice egg. 8/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_09',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_09',
		description = "That's a nice egg. 9/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_10',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_10',
		description = "That's a nice egg. 10/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_11',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_11',
		description = "That's a nice egg. 11/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_12',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_12',
		description = "That's a nice egg. 12/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_13',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_13',
		description = "That's a nice egg. 13/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_14',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_14',
		description = "That's a nice egg. 14/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_15',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_15',
		description = "That's a nice egg. 15/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_16',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_16',
		description = "That's a nice egg. 16/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_17',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_17',
		description = "That's a nice egg. 17/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_18',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_18',
		description = "That's a nice egg. 18/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_19',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_19',
		description = "That's a nice egg. 19/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_20',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_20',
		description = "That's a nice egg. 20/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_21',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_21',
		description = "That's a nice egg. 21/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_22',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_22',
		description = "That's a nice egg. 22/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_23',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_23',
		description = "That's a nice egg. 23/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'dl_egg_24',
		label = 'Easter Egg',
		iconOverride = 'easter_egg_24',
		description = "That's a nice egg. 24/24",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
	},
	{
		name = 'bronze_egg',
		label = 'Bronze Easter Egg',
		iconOverride = 'easter_bronze_egg',
		description = "That's a nice egg",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = 'silver_egg',
		label = 'Silver Easter Egg',
		iconOverride = 'easter_silver_egg',
		description = "That's a nice egg",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = 'gold_egg',
		label = 'Gold Easter Egg',
		iconOverride = 'easter_gold_egg',
		description = "That's a nice egg",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = 'diamond_egg',
		label = 'Diamond Easter Egg',
		iconOverride = 'easter_diamond_egg',
		description = "That's a nice egg",
		isUsable = true,
		isStackable = false,
		isDestroyed = true,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
}
