_itemsSource["tools"] = {
	{
		name = "lockpick",
		label = "Lockpick",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = 50,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "metal_detector",
		label = "Metal Detector",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 4.0,
		durability = (60 * 60 * 24 * 21),
	},
		{
                name = "trowel",
                label = "Trowel",
                description = "Cool its a trowel",
                price = 450,
                isUsable = true,
                isRemoved = false,
                isStackable = false,
                type = 3,
                rarity = 1,
                closeUi = true,
                metalic = true,
                weight = 2.0,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "adv_lockpick",
		label = "Advanced Lockpick",
		price = 600,
		isUsable = true,
		isRemoved = false,
		isStackable = 20,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		durability = (60 * 60 * 24 * 28),
	},
	{
		name = "lockpick_pd",
		label = "PD Lockpick",
		description = "Only Usable By Police",
		iconOverride = "lockpick",
		imitate = "lockpick",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = 10,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		useRestrict = {
			job = {
				id = "police",
				duty = true,
			},
		}
	},
	{
		name = "screwdriver",
		label = "Screwdriver",
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.4,
		durability = (60 * 60 * 24 * 3),
	},
	{
		name = "racing_crappy",
		label = "Homemade Racing Dongle",
		description = "Its a really shitty racing dongle",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		state = "RACE_DONGLE",
		weight = 1,
		durability = (60 * 60 * 12),
	},
	{
		name = "racedongle",
		label = "Racing Phone Dongle V2",
		description = "Its a Racing Phone Dongle",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		state = "RACE_DONGLE",
		weight = 2.5,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "vpn",
		label = "VPN",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		state = "PHONE_VPN",
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "pickaxe",
		label = "Pickaxe",
		price = 0,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 4.0,
		durability = (60 * 60 * 24 * 1),
	},
	{
		name = "pdhandcuffs",
		label = "PD Handcuffs",
		price = 25,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.25,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "handcuffs",
		label = "Handcuffs",
		price = 600,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "fluffyhandcuffs",
		label = "Fluffy Handcuffs",
		price = 600,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "spikes",
		label = "Spike Strips",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "binoculars",
		label = "Binoculars",
		price = 90,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 2.5,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "camera",
		label = "Camera",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 2.5,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "gps_tracker",
		label = "Gruppe 6 Truck Tracker",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "bobcat_tracker",
		label = "Bobcat Truck Tracker",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "fleeca_tracker",
		label = "Fleeca Truck Tracker",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "bkvan_tracker",
		label = "Van Tracker",
		iconOverride = 'fleeca_tracker',
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "meth_table",
		label = "Meth Table",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "parachute",
		label = "Parachute",
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	-- Ingedients
	{
		name = "acetone",
		label = "Acetone",
		price = 25,
		isUsable = false,
		isRemoved = false,
		isStackable = 100,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.25,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "battery_acid",
		label = "Battery Acid",
		price = 25,
		isUsable = false,
		isRemoved = false,
		isStackable = 100,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.25,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "iodine_crystals",
		label = "Iodine Crystals",
		price = 25,
		isUsable = false,
		isRemoved = false,
		isStackable = 100,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.25,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "racingtablet",
		iconOverride = "racingtablet",
		label = "Racing tablet",
		description = 'Seems like something\'s installed on this.<br><i>Marked For Police Seizure</i>',
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 5,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "boostingtablet",
		iconOverride = "boostingtablet",
		label = "Boosting tablet",
		description = 'Seems like something\'s installed on this.<br><i>Marked For Police Seizure</i>',
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 5,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "hackingdevice",
		iconOverride = "hackingdevice",
		label = "Hacking Device",
		description = 'Advanced Vehicle Hacking Device.<br><i>Marked For Police Seizure</i>',
		price = 3000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 14,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "gpshackingdevice",
		iconOverride = "gpshackingdevice",
		label = "GPS Hacking Device",
		description = 'If you wish to disable vehicle GPS systems.',
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 14,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "bodycam",
		label = "Bodycam",
		price = 0,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 2.0,
		durability = (60 * 60 * 24 * 21),
		description = "Bodycam for police officers!",
	},
	{
		name = "dashcam",
		label = "Dashcam",
		price = 0,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 2.0,
		durability = (60 * 60 * 24 * 21),
		description = "Dashcam for police officers Vehicles!",
	},
}
