_itemsSource['weapons_base'] = {
	{
		name = 'WEAPON_SMG',
		label = 'SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = 'WEAPON_MP5',
		weapon = 'WEAPON_MP5',
		iconOverride = 'WEAPON_SMG',
		label = 'Tactical SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = 'WEAPON_PP19',
		label = 'Compact PDW',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = 'WEAPON_MP9A',
		weapon = 'WEAPON_MP9A',
		label = 'Subcompact SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = 'WEAPON_MPX',
		label = 'Compact PDW',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = 'WEAPON_MINIUZI',
		label = 'Mini SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = 'WEAPON_BALL',
		label = 'Ball',
		ammoType = 'AMMO_BALL',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		isThrowable = true,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = 'WEAPON_SNOWBALL',
		label = 'Snowball',
		ammoType = 'AMMO_SNOWBALL',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		isThrowable = true,
		durability = (60 * 60 * 24),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = 'WEAPON_GRENADE',
		label = 'Grenade',
		ammoType = 'AMMO_GRENADE',
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_BZGAS',
		label = 'BZ Gas',
		ammoType = 'AMMO_BZGAS',
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_MOLOTOV',
		label = 'Molotov',
		ammoType = 'AMMO_MOLOTOV',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 5,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = 'WEAPON_STICKYBOMB',
		label = 'Sticky Bomb',
		ammoType = 'AMMO_STICKYBOMB',
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = 'WEAPON_PROXMINE',
		label = 'Proximity Mine',
		ammoType = 'AMMO_PROXMINE',
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = 'WEAPON_PIPEBOMB',
		label = 'Pipe Bomb',
		ammoType = 'AMMO_PIPEBOMB',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = 'WEAPON_SMOKEGRENADE',
		label = 'Smoke Grenade',
		ammoType = 'AMMO_SMOKEGRENADE',
		qualification = 'PD_SWAT',
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		storeStack = 1,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = 'WEAPON_FLASHBANG',
		label = 'Flashbang',
		ammoType = 'AMMO_FLASH',
		qualification = 'PD_SWAT',
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		storeStack = 1,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = 'WEAPON_FLARE',
		label = 'Flare',
		ammoType = 'AMMO_FLARE',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 14),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_FIREEXTINGUISHER',
		label = 'Fire Extinguisher',
		ammoType = 'AMMO_FIREEXTINGUISHER',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 21),
		type = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_PETROLCAN',
		label = 'Petrol Can',
		ammoType = 'AMMO_PETROLCAN',
		requiresLicense = false,
		noSerial = true,
		price = 150,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 10,
	},
	{
		name = 'WEAPON_CROWBAR',
		label = 'Crowbar',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_BAT',
		label = 'Baseball Bat',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 10,
	},
	{
		name = 'WEAPON_LUCILLE',
		label = 'Lucille',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 10,
	},
	{
		name = 'WEAPON_GAS',
		label = 'Gascan',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 10,
	},
	{
		name = 'WEAPON_CRUTCH',
		label = 'Crutch',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 10,
	},
	{
		name = 'WEAPON_SLEDGE',
		label = 'Sledge Hammer',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 12,
	},
	{
		name = 'WEAPON_SHOVEL',
		label = 'Shovel',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 10,
	},
	{
		name = 'WEAPON_DAGGER',
		label = 'Dagger',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_MACHETE',
		label = 'Machete',
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_PONY',
		label = 'Pony',
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_SLEDGE',
		label = 'Sledgehammer',
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = 'WEAPON_KNIFE',
		label = 'Knife',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8.5,
	},
	{
		name = 'WEAPON_SWITCHBLADE',
		label = 'Switchblade',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = 'WEAPON_BOTTLE',
		label = 'Broken Bottle',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = 'WEAPON_WRENCH',
		label = 'Pipe Wrench',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_BATTLEAXE',
		label = 'Battle Axe',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 18,
	},
	{
		name = 'WEAPON_HATCHET',
		label = 'Hatchet',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 18,
	},
	{
		name = 'WEAPON_STONE_HATCHET',
		label = 'Stone Hatchet',
		requiresLicense = false,
		noSerial = true,
		price = 300,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 12,
	},
	{
		name = 'WEAPON_HAMMER',
		label = 'Hammer',
		requiresLicense = false,
		noSerial = true,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = "WEAPON_BAQUETTE",
		weapon = 'WEAPON_BREAD',
		label = "Baquette",
		requiresLicense = false,
		noSerial = true,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
	},
	{
		name = 'WEAPON_GOLFCLUB',
		label = 'Golf Club',
		requiresLicense = false,
		noSerial = true,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = 'WEAPON_KNUCKLE',
		label = 'Knuckle Dusters',
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 7.5,
	},
	{
		name = 'WEAPON_POOLCUE',
		label = 'Pool Cue',
		requiresLicense = false,
		noSerial = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 10,
	},
	{
		name = 'WEAPON_FLASHLIGHT',
		label = 'Flashlight',
		requiresLicense = false,
		noSerial = true,
		price = 75,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = 'WEAPON_NIGHTSTICK',
		label = 'Nightstick',
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = 'WEAPON_PISTOL',
		label = 'Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_COMBATPISTOL',
		label = 'Combat Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_FNX',
		label = 'Combat .45',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_APPISTOL',
		label = 'AP Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_VINTAGEPISTOL',
		label = 'Vintage Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 5500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_HEAVYPISTOL',
		label = 'Heavy Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_P320a',
		label = 'Modular 320',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_SNSPISTOL',
		label = 'SNS Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = 'WEAPON_SNSPISTOL_MK2',
		label = 'SNS Pistol MK2',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 4500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = 'WEAPON_FLAREGUN',
		label = 'Flare Gun',
		ammoType = 'AMMO_FLAREGUN',
		requiresLicense = false,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_MARKSMANPISTOL',
		label = 'Marksman Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 7500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_REVOLVER',
		label = 'Revolver',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_REVOLVER_MK2',
		label = 'Heavy Revolver Mk II',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_DOUBLEACTION',
		label = 'Double-Action Revolver',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_PISTOL50',
		label = 'Pistol .50',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_PISTOL_MK2',
		label = 'Pistol Mk II',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 2500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_MICROSMG',
		label = 'Micro SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_UZI',
		label = 'Street SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_MINISMG',
		label = 'Mini SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isDestroyed = false,
		isStackable = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_SMG_MK2',
		label = 'SMG Mk II',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_ASSAULTSMG',
		label = 'Assault SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_COMBATPDW',
		label = 'Combat PDW',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_MACHINEPISTOL',
		label = 'Machine Pistol',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_GUSENBERG',
		label = 'Gusenberg Sweeper',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_MG',
		label = 'MG',
		ammoType = 'AMMO_MG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = 'WEAPON_COMBATMG',
		label = 'Combat MG',
		ammoType = 'AMMO_MG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = 'WEAPON_COMBATMG_MK2',
		label = 'Combat MG Mk II',
		ammoType = 'AMMO_MG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = 'WEAPON_MUSKET',
		label = 'Musket',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_BEANBAG',
		label = 'Beanbag Gun',
		ammoType = 'AMMO_SHOTGUN',
		qualification = 'PD_BEANBAG',
		requiresLicense = true,
		price = 300,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_SAWNOFFSHOTGUN',
		label = 'Sawed-Off Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_PUMPSHOTGUN',
		label = 'Pump Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_PUMPSHOTGUN_MK2',
		label = 'Pump Shotgun Mk II',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_BULLPUPSHOTGUN',
		label = 'Bullpup Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_ASSAULTSHOTGUN',
		label = 'Assault Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_DBSHOTGUN',
		label = 'Double Barrel Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_HEAVYSHOTGUN',
		label = 'Heavy Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_AUTOSHOTGUN',
		label = 'Sweeper Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_ASSAULTRIFLE',
		label = 'Assault Rifle',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_AK74',
		label = 'Compact Assault Rifle',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_50BEOWULF',
		label = 'Heavy .50 Carbine',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_AR15',
		label = 'Sport Rifle',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_57',
		label = 'Viper Pistol',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_P90FM',
		label = 'Bullpup SMG',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_HKUMP',
		label = 'PD SMG .45',
		ammoType = 'AMMO_SMG',
		qualification = 'PD_SMG',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 3),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_ASSAULTRIFLE_MK2',
		label = 'Assault Rifle Mk II',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_CARBINERIFLE',
		label = 'Carbine Rifle',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_CARBINERIFLE_MK2',
		label = 'Carbine Rifle Mk II',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_HK416B',
		label = 'PD Carbine',
		ammoType = 'AMMO_RIFLE',
		qualification = 'PD_AR',
		requiresLicense = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 3),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_COMPACTRIFLE',
		label = 'Compact Rifle',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_BULLPUPRIFLE',
		label = 'Bullpup Rifle',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_BULLPUPRIFLE_MK2',
		label = 'Bullpup Rifle Mk II',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_ADVANCEDRIFLE',
		label = 'Advanced Rifle',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_SPECIALCARBINE',
		label = 'Special Carbine',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_SPECIALCARBINE_MK2',
		label = 'Special Carbine Mk II',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_SNIPERRIFLE',
		label = 'Sniper Rifle',
		ammoType = 'AMMO_SNIPER',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_MARKSMANRIFLE',
		label = 'Marksman Rifle',
		ammoType = 'AMMO_SNIPER',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_MARKSMANRIFLE_MK2',
		label = 'Marksman Rifle Mk II',
		ammoType = 'AMMO_SNIPER',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_HEAVYSNIPER',
		label = 'Heavy Sniper',
		ammoType = 'AMMO_SNIPER',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_HEAVYSNIPER_MK2',
		label = 'Heavy Sniper Mk II',
		ammoType = 'AMMO_SNIPER',
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'WEAPON_GRENADELAUNCHER_SMOKE',
		label = 'Smoke Grenade Launcher',
		ammoType = 'AMMO_GRENADELAUNCHER_SMOKE',
		requiresLicense = true,
		price = 100000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
	},
	{
		name = 'WEAPON_FIREWORK',
		label = 'Firework Launcher',
		ammoType = 'AMMO_FIREWORK',
		requiresLicense = false,
		price = 100000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 20,
	},
	-- {
	-- 	name = 'WEAPON_STUNGUN',
	-- 	label = 'Stun Gun',
	-- 	ammoType = 'AMMO_STUNGUN',
	-- 	requiresLicense = false,
	-- 	price = 1000,
	-- 	isUsable = true,
	-- 	isRemoved = false,
	-- 	isStackable = false,
	-- 	isDestroyed = false,
	-- 	durability = (60 * 60 * 24 * 21),
	-- 	type = 2,
	-- 	rarity = 1,
	-- 	closeUi = true,
	-- 	metalic = true,
	-- 	weight = 1,
	-- },
	{
		name = 'WEAPON_TASER',
		label = 'Stun Gun',
		ammoType = 'AMMO_STUNGUN',
		requiresLicense = false,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = 'WEAPON_SNIPERRIFLE2',
		label = 'Hunting Rifle',
		ammoType = 'AMMO_SNIPER',
		requiresLicense = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = 'TESTPISTOL',
		label = 'Test Pistol',
		weapon = 'WEAPON_PISTOL',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
		staticMetadata = {
			WeaponTint = 2,
		},
	},
	{
		name = 'KATANA',
		label = 'Katana',
		weapon = 'WEAPON_KATANA',
		ammoType = 'NONE',
		requiresLicense = false,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 3,
	},
	{
		name = "KATANA2",
		label = "Thermal Katana",
		weapon = "WEAPON_KATANA2",
		iconOverride = "WEAPON_KATANA2",
		ammoType = "NONE",
		requiresLicense = false,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 3,
	},
	{
		name = "KATANA3",
		label = "Thermal Katana",
		weapon = "WEAPON_KATANA3",
		iconOverride = "WEAPON_KATANA3",
		ammoType = "NONE",
		requiresLicense = false,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 3,
	},
	{
		name = 'SHIV',
		label = 'Shiv',
		weapon = 'WEAPON_SHIV',
		ammoType = 'NONE',
		requiresLicense = false,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
	},
	{
		name = 'WEAPON_L5',
		label = 'Light .50',
		iconOverride = 'WEAPON_PISTOL50',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_P3200A',
		label = '320 X Custom',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_G45',
		label = 'Service 45',
		iconOverride = 'WEAPON_G17',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_M45A1',
		label = 'Service .45 A1',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_2011',
		label = 'Race 2011',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_G36',
		label = 'Tactical Carbine',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_RPK16',
		label = 'Heavy Carbine',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_FLAMETHROWER',
		label = 'Flamethrower',
		ammoType = 'AMMO_FLAMETHROWER',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_MINIGUN',
		label = 'Minigun',
		ammoType = 'AMMO_MINIGUN',
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
}
